### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils' 

### ISSUE THREAD

**Issue by egarbi** [Agilicus/pre-commit-hook-k8svalidate#5]
After upgrading python to v3.12 on my Mac. I'm not able anymore to validate commits.
See the full error below
```
k8svalidate..............................................................Failed
- hook id: k8svalidate
- exit code: 1

Traceback (most recent call last):
  File "/Users/enrique/.cache/pre-commit/repocsm9mirn/py_env-python3.12/bin/k8svalidate", line 13, in <module>
    import kubernetes_validate.utils as utils
  File "/Users/enrique/.cache/pre-commit/repocsm9mirn/py_env-python3.12/lib/python3.12/site-packages/kubernetes_validate/__init__.py", line 1, in <module>
    from .utils import latest_version, validate, validate_file, validate_resource
  File "/Users/enrique/.cache/pre-commit/repocsm9mirn/py_env-python3.12/lib/python3.12/site-packages/kubernetes_validate/utils.py", line 8, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```
This is my configuration file
```
- repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
    rev: v0.2.0
    hooks:
      - id: k8svalidate
        files: .yaml$
```
`kubernetes-validate` CLI works if I try manually
```
❯ kubernetes-validate -k 1.28 --strict namespace.yaml
INFO namespace.yaml passed for resource namespace/laravel-queue-workers against version 1.28
```

**Comment by brent-cybrid** [comment]
I'm also running into this issue after updating Python to v3.12. It is related to `distutils` no longer being supported in Python v3.12 (see [here](https://docs.python.org/3.10/library/distutils.html)).

**Comment by donbowman** [comment]
we don't use distutils in this tho?

**Comment by brent-cybrid** [comment]
It's due to an issue with a dependency of this project: [`kubernetes-validate`](https://github.com/willthames/kubernetes-validate).

I've opened a ticket with them as well [here](https://github.com/willthames/kubernetes-validate/issues/24).

Here's the error message that is received this package is run:

```
Traceback (most recent call last):
  File "<user_dir>/.cache/pre-commit/repotkgmzlfm/py_env-python3.12/bin/k8svalidate", line 13, in <module>
    import kubernetes_validate.utils as utils
  File "<user_dir>.cache/pre-commit/repotkgmzlfm/py_env-python3.12/lib/python3.12/site-packages/kubernetes_validate/__init__.py", line 1, in <module>
    from .utils import latest_version, validate, validate_file, validate_resource
  File "<user_dir>/.cache/pre-commit/repotkgmzlfm/py_env-python3.12/lib/python3.12/site-packages/kubernetes_validate/utils.py", line 8, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

**Comment by egarbi** [comment]
This has been solved by https://github.com/willthames/kubernetes-validate/issues/24
